config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'
  get 'landing/autocomplete_organization_name'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/search/results', to: 'search#index'

  get '/topics', to: 'tags#index'

  resources :users, only: [:new, :create, :show]
  resources :organizations, only: [:index, :show], param: :slug, path: "o"
  resources :categories, only: [:index, :show]

  namespace :organizations, only: [:show], path: "o" do
    resources :offerings, only: [:show], param: :slug, path: "of"
  end

  namespace :admin do
    get '/dashboard', to: 'dashboard#show'
    patch '/dashboard', to: 'dashboard#update'
    resources :organizations, only: [:new, :create, :edit, :update, :show]
    get '/:organization/offering/new', to: 'offerings#new', as: 'new_offering'
    post '/:organization/offering/new', to: 'offerings#create'
    resources :offerings, only: [:new, :create, :show, :destroy, :edit, :update]
    resources :tags
    resources :categories
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    if params["qt"] &&  params["qf"] && params["q"] == ""
      results_tag = Offering.search(params["qt"])
      results_format = Offering.search_format(params["qf"])
      if results_tag == nil
        @results = results_format
      elsif results_format == nil
        @results = results_tag
      else
        @results = results_tag + results_format
      end
    end
    if params["q"] && params["qt"] == "" && params["qf"] == ""
      @results = Organization.by_search(params["q"])
    end
    if params[:sort]
      sort_results
    end
  end

  private

  def sort_results
    if params[:sort] == "az"
      if params["qt"] && params["q"] == ""
        @results = Offering.search(params["qt"]).order('offerings.name ASC')
      else
        @results = Organization.by_search(params["q"]).reverse
      end
    end
    if params[:sort] == "za"
      if params["qt"] && params["q"] == ""
        @results = Offering.search(params["qt"]).order('offerings.name DESC')
      else
        @results = Organization.by_search(params["q"])
      end
    end
    if params[:sort] == "price"
      if params["qt"] && params["q"] == ""
        @results = Offering.search(params["qt"]).order('offerings.price DESC')
      else
        @results = Organization.by_search(params["q"])
      end
    end
    if params[:sort] == "new"
      if params["qt"] && params["q"] == ""
        @results = Offering.search(params["qt"])
      else
        @results = Organization.by_search(params["q"])
      end
    end
  end


end

app/views/search/index.html.erb
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">


<div class="container">
  <div class="dropdown-sort" style="float:left; width:19%;">
    <button class="dropbtn">PRICE  <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span></button>
    <div class="dropdown-content">
      <a href='/search/results?cat=learning&q=<%=params[:q]%>&qt=<%=params[:qt]%>&filter=price&price=free'>Free</a>
      <a href='/search/results?cat=learning&q=<%=params[:q]%>&qt=<%=params[:qt]%>&filter=price&proce=25'>Under $25</a>
    </div>
  </div>

  <div class="dropdown-sort" style="float:left; width:19%;">
    <button class="dropbtn">LOCATION <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span></button>
    <div class="dropdown-content">
      <a href='/search/results?cat=learning&q=<%=params[:q]%>&qt=<%=params[:qt]%>&filter=location&location=denver'>Denver</a>
      <a href='/search/results?cat=learning&q=<%=params[:q]%>&qt=<%=params[:qt]%>&filter=location&location=boston'>Boston</a>
    </div>
  </div>

  <div class="dropdown-sort" style="float:left; width:20%;">
    <button class="dropbtn">TOPIC <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span></button>
    <div class="dropdown-content">
      <a href='/search/results?cat=learning&q=<%=params[:q]%>&qt=<%=params[:qt]%>&filter=topic&format=socialmedia'>Social Media</a>
      <a href='/search/results?cat=learning&q=<%=params[:q]%>&qt=<%=params[:qt]%>&filter=topic&format=business'>Business</a>
    </div>
  </div>

  <div class="dropdown-sort" style="float:left; width:19%;">
    <button class="dropbtn">FORMAT <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span></button>
    <div class="dropdown-content">
      <a href='/search/results?cat=learning&q=<%=params[:q]%>&qt=<%=params[:qt]%>&filter=format&format=conference'>Conference</a>
      <a href='/search/results?cat=learning&q=<%=params[:q]%>&qt=<%=params[:qt]%>&filter=format&format=webinar'>Webinar</a>
    </div>
  </div>

  <div class="dropdown-sort" style="float:left; width:19%;">
    <button class="dropbtn">LENGTH <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span></button>
    <div class="dropdown-content">
      <a href='/search/results?cat=learning&q=<%=params[:q]%>&qt=<%=params[:qt]%>&filter=length&length=weekly'>Daily</a>
      <a href='/search/results?cat=learning&q=<%=params[:q]%>&qt=<%=params[:qt]%>&filter=lenght&length=daily'>Weekly</a>
    </div>
  </div>
</div>

<div style="float:right; width:30%; padding-top:3em; font-family:Lora;">
  <span id="sort-results"> Sort by: </span>
  <button class="sort-order"> <a href='/search/results?sort=az&q=<%=params[:q]%>&qt=<%=params[:qt]%>&cat=<%=params[:cat]%>'>A - Z </a> </button>
  <button class="sort-order"> <a href='/search/results?sort=za&q=<%=params[:q]%>&qt=<%=params[:qt]%>&cat=<%=params[:cat]%>'>Z - A </a> </button>
  <button class="sort-order"> <a href='/search/results?sort=price&q=<%=params[:q]%>&qt=<%=params[:qt]%>&cat=<%=params[:cat]%>'>PRICE </a> </button>
  <button class="sort-order"> <a href='/search/results?sort=new&q=<%=params[:q]%>&qt=<%=params[:qt]%>&cat=<%=params[:cat]%>'>NEWEST </a> </button>
</div>

<div class="container">
  <% if @results == nil %>
  <h4> Sorry, there were no results.</h4>
  <% else %>
  <div class="row" style="padding-top:7em;">
    <% @results.each do |result| %>
      <div class="col-md-4" style="overflow:scroll">
        <div class="image">
            <% if result.class == Organization %>
              <%= link_to image_tag(result.avatar.url(:square)), organization_path(result), class: "search-image" %>
            <% end %>
            <% if result.class == Offering %>
              <% if result.avatar_file_name == nil  %>
                <%= link_to image_tag(result.organization.avatar.url(:square)), organizations_offering_path(result), class: "search-image" %>
              <% else %>
                <%= link_to image_tag(result.avatar.url(:square)), organizations_offering_path(result), class: "search-image" %>
              <% end %>
            <% end %>
        </div>
        <% if result.class == Organization %>
          <%= link_to result.name.titleize, organization_path(result) %><br>
        <% end %>
        <% if result.class == Offering %>
          <%= link_to result.name.titleize, organizations_offering_path(result) %><br>
        <% end %>

        <% if result.class == Organization %>
          <% result.categories.each do |category| %>
            <span class="label label-default"><%= link_to category.name, category_path(category) %></span>
          <% end %>
        <% elsif  %>
          <% result.tags.each do |tag| %>
            <span class="label label-default"><%#= link_to tag.name, category_path(category) %></span>
          <% end %>
        <% end %>

        <% if result.class == Offering %>
          <% link_to result.name.titleize, organizations_offering_path(result) %>
        <% end %>
      </div>
    <% end %>

  <% end %>
</div>
</div>