config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'
  get 'landing/autocomplete_organization_name'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/search/results', to: 'search#index'

  get '/topics', to: 'tags#index'

  resources :users, only: [:new, :create, :show]
  resources :organizations, only: [:index, :show], param: :slug, path: "o"
  resources :categories, only: [:index, :show]

  namespace :organizations, only: [:show], path: "o" do
    resources :offerings, only: [:show], param: :slug, path: "of"
  end

  namespace :admin do
    get '/dashboard', to: 'dashboard#show'
    patch '/dashboard', to: 'dashboard#update'
    resources :organizations, only: [:new, :create, :edit, :update, :show]
    get '/:organization/offering/new', to: 'offerings#new', as: 'new_offering'
    post '/:organization/offering/new', to: 'offerings#create'
    resources :offerings, only: [:new, :create, :show, :destroy, :edit, :update]
    resources :tags
    resources :categories
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController

  before_action :require_admin

  def require_admin
    render file: 'public/404' unless current_admin?
  end

  def show
    if params[:letter]
      @organizations = Organization.by_letter(params[:letter])
    else
      @organizations = Organization.all
    end
  end

end

app/views/admin/dashboard/_letters.html.erb
<div class="text-center">
  <nav aria-label="Page navigation">
    <ul class="pagination">
      <li><%= link_to 'ALL', admin_dashboard_path %></li>
      <li><%= link_to 'A', admin_dashboard_path(:letter => 'A') %></li>
      <li><%= link_to 'B', admin_dashboard_path(:letter => 'B') %></li>
      <li><%= link_to 'C', admin_dashboard_path(:letter => 'C') %></li>
      <li><%= link_to 'D', admin_dashboard_path(:letter => 'D') %></li>
      <li><%= link_to 'E', admin_dashboard_path(:letter => 'E') %></li>
      <li><%= link_to 'F', admin_dashboard_path(:letter => 'F') %></li>
      <li><%= link_to 'G', admin_dashboard_path(:letter => 'G') %></li>
      <li><%= link_to 'H', admin_dashboard_path(:letter => 'H') %></li>
      <li><%= link_to 'I', admin_dashboard_path(:letter => 'I') %></li>
      <li><%= link_to 'J', admin_dashboard_path(:letter => 'J') %></li>
      <li><%= link_to 'K', admin_dashboard_path(:letter => 'K') %></li>
      <li><%= link_to 'L', admin_dashboard_path(:letter => 'L') %></li>
      <li><%= link_to 'M', admin_dashboard_path(:letter => 'M') %></li>
      <li><%= link_to 'N', admin_dashboard_path(:letter => 'N') %></li>
      <li><%= link_to 'O', admin_dashboard_path(:letter => 'O') %></li>
      <li><%= link_to 'P', admin_dashboard_path(:letter => 'P') %></li>
      <li><%= link_to 'Q', admin_dashboard_path(:letter => 'Q') %></li>
      <li><%= link_to 'R', admin_dashboard_path(:letter => 'R') %></li>
      <li><%= link_to 'S', admin_dashboard_path(:letter => 'S') %></li>
      <li><%= link_to 'T', admin_dashboard_path(:letter => 'T') %></li>
      <li><%= link_to 'U', admin_dashboard_path(:letter => 'U') %></li>
      <li><%= link_to 'V', admin_dashboard_path(:letter => 'V') %></li>
      <li><%= link_to 'W', admin_dashboard_path(:letter => 'W') %></li>
      <li><%= link_to 'X', admin_dashboard_path(:letter => 'X') %></li>
      <li><%= link_to 'Y', admin_dashboard_path(:letter => 'Y') %></li>
      <li><%= link_to 'Z', admin_dashboard_path(:letter => 'Z') %></li>
      <li><%= link_to 'ALL', admin_dashboard_path %></li>
    </ul>
  </nav>
</div>

app/views/admin/dashboard/show.html.erb
<div class="container">
  <h2 id="admin-header-dashboard"> Welcome to Your Admin Dashboard</h2>
  <div class="well">
    <div class="panel-body">
      <div class="row">
        <div class="col-md-4">
          <h4 style="text-align:center; padding-top:10px;"><%= link_to "Add An Organization Here", new_admin_organization_path, class: "btn btn-success" %></h4>
        </div>
        <div class="col-md-4">
          <h4 style="text-align:center; padding-top:10px;"><%= link_to "Manage Categories Here", new_admin_category_path, class: "btn btn-success" %></h4>
        </div>
        <div class="col-md-4">
          <h4 style="text-align:center; padding-top:10px;"><%= link_to "Manage Tags Here", new_admin_tag_path, class: "btn btn-success" %></h4>
        </div>
      </div>
    </div>
  </div>
  <div id="current-organizations">
    <h3 style="text-align:center;">Current Organizations:</h3>
    <%= render partial: "admin/dashboard/letters" %>

      <% @organizations.each do |organization| %>
      <div class="panel panel-default">
        <div class="panel-heading"><h4><%= link_to organization.name.titleize, admin_organization_path(organization.id) %></h4></div>
          <div class="panel-body">
            <div class="row">
              <div class="col-md-6">
                <%= image_tag organization.avatar.url(:square) %>
                <h5></h5>
                <%= link_to "Edit This Organization", edit_admin_organization_path(organization.id), class: "btn btn-warning btn-sm" %>
              </div>
              <div class="col-md-6">
                <h4><%= organization.name.titleize %>'s current offerings are:</h4>
                <% organization.offerings.each do |offering| %>
                <h5><%= link_to offering.name.titleize, admin_offering_path(offering.id) %> - <%= offering.format %>
                <% end %>
                <h5><%= link_to "Add an offering for this organization", admin_new_offering_path(organization.id), class: "btn btn-info btn-sm" %></h5>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>