config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'
  get 'landing/autocomplete_organization_name'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/search/results', to: 'search#index'

  get '/topics', to: 'tags#index'

  resources :users, only: [:new, :create, :show]
  resources :organizations, only: [:index, :show], param: :slug, path: "o"
  resources :categories, only: [:index, :show]

  namespace :organizations, only: [:show], path: "o" do
    resources :offerings, only: [:show], param: :slug, path: "of"
  end

  namespace :admin do
    get '/dashboard', to: 'dashboard#show'
    patch '/dashboard', to: 'dashboard#update'
    resources :organizations, only: [:new, :create, :edit, :update, :show]
    get '/:organization/offering/new', to: 'offerings#new', as: 'new_offering'
    post '/:organization/offering/new', to: 'offerings#create'
    resources :offerings, only: [:new, :create, :show, :destroy, :edit, :update]
    resources :tags
    resources :categories
  end

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ApplicationRecord
  has_many :offerings_tags, :dependent => :nullify
  has_many :offerings, through: :offerings_tags, :dependent => :nullify
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController

  def new
    @tag = Tag.new
    @tags = Tag.all
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to new_admin_tag_path
      flash[:success] = "Created new tag #{@tag.name}"
    else
      flash.now[:error] = "Please try again."
      render :new
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    @tag.update(tag_params)
    flash[:success] = "Successfully updated #{@tag.name}"
    redirect_to new_admin_tag_path
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to new_admin_tag_path
    flash[:success] = "Successfully deleted #{@tag.name}."
  end

  private
    def tag_params
      params.require(:tag).permit(:name)
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @topics = Tag.all
  end

end

app/views/admin/tags/edit.html.erb
<body class="login-page">
  <div class="container extra-pad">
    <div class ="row">
      <div class = "text-center">
        <div class="col-sm-3">
        </div>
        <div class="col-sm-6">
          <div class="panel panel-default">
            <div class="panel-body less-padding">
              <h3 class="form-title">Update <%= @tag.name.titleize %> </h3>
            </div>
            <div class="panel-footer panel-pad">
              <%= form_for [:admin, @tag], class: "form-group" do |f| %>
                <div class="form-group">
                  <%= f.text_field :name, class: "form-control login-items", placeholder: "Name", id: "Name" %>
                </div>
                <button type="submit" class="btn btn-default submit-button login-items" id="submitnewbutton">Update Tag</button></p>
              <% end %>
              </div>
            </div>

            <p style ="padding-top:50px"><%= link_to " << Back to Your Dashboard", admin_dashboard_path, class: "btn btn-success btn-sm"%></p>
          </div>
          <div class="col-sm-3">
          </div>
        </div>
      </div>
    </body>

app/views/admin/tags/new.html.erb
<body class="login-page">
  <div class="container extra-pad">
    <div class ="row">
      <div class = "text-center">
        <div class="col-sm-3">
        </div>
        <div class="col-sm-6">
          <div class="panel panel-default">
            <div class="panel-body less-padding">
              <h3 class="form-title">Create a New Tag </h3>
            </div>
            <div class="panel-footer panel-pad">
              <%= form_for [:admin, @tag], class: "form-group" do |f| %>
                <div class="form-group">
                  <%= f.text_field :name, class: "form-control login-items", placeholder: "Name", id: "Name" %>
                </div>
                <button type="submit" class="btn btn-default submit-button login-items" id="submitnewbutton">Create Tag</button></p>
              <% end %>
              </div>
            </div>
            <h3>Current Tags:</h3>
            <% @tags.each do |tag| %>
            <p><%= tag.name.titleize %> <%= link_to "Edit This Tag", edit_admin_tag_path(tag), class: "btn btn-info btn-sm" %> <%= link_to "Delete This Tag", admin_tag_path(tag), method: :delete, class: "btn btn-warning btn-sm",  data: { confirm: 'Are you sure you want to delete this tag?' } %></p>
            </p>
            <% end %>
            <p style ="padding-top:50px"><%= link_to " << Back to Your Dashboard", admin_dashboard_path, class: "btn btn-success btn-sm"%></p>
          </div>
          <div class="col-sm-3">
          </div>
        </div>
      </div>
    </body>