config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'
  get 'landing/autocomplete_organization_name'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/search/results', to: 'search#index'

  get '/topics', to: 'tags#index'

  resources :users, only: [:new, :create, :show]
  resources :organizations, only: [:index, :show], param: :slug, path: "o"
  resources :categories, only: [:index, :show]

  namespace :organizations, only: [:show], path: "o" do
    resources :offerings, only: [:show], param: :slug, path: "of"
  end

  namespace :admin do
    get '/dashboard', to: 'dashboard#show'
    patch '/dashboard', to: 'dashboard#update'
    resources :organizations, only: [:new, :create, :edit, :update, :show]
    get '/:organization/offering/new', to: 'offerings#new', as: 'new_offering'
    post '/:organization/offering/new', to: 'offerings#create'
    resources :offerings, only: [:new, :create, :show, :destroy, :edit, :update]
    resources :tags
    resources :categories
  end

end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id                  :integer          not null, primary key
#  name                :string
#  website             :string
#  instagram           :string
#  twitter             :string
#  facebook            :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  description         :string
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  history             :string
#  slug                :string
#

class Organization < ApplicationRecord
  has_many :offerings
  has_many :organizations_categories
  has_many :categories, through: :organizations_categories
  # after_save :set_slug


  scope :by_letter, ->(initial) {where("LOWER(name) LIKE \'#{initial.downcase}%\'").order(:name) }

  scope :by_search, ->(term) {where("LOWER(name) LIKE \'#{term.downcase}%\'").order(:name) }

  validates :name, presence: true

  has_attached_file :avatar,
    styles: {
      thumb: '100x100>',
      square: '200x200#',
      medium: '300x300>'
    },
    :default_url => '/assets/icon-missing.png',
    s3_region: ENV["AWS_REGION"]

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.search(search)
    where("name LIKE ?", "%#{search.downcase}%")
  end

  def self.filter(filter)
    joins(:categories).where(:categories => {:id => filter})
  end

  def self.search_similar(org)
    if org.categories != []
      joins(:categories).where("category_id = #{org.categories.first.id}")
    end
  end

  def courses
    self.offerings.where("LOWER(format) LIKE?", "%course" )
  end

  def workshops
    self.offerings.where("LOWER(format) LIKE?", "workshop")
  end

  def consulting
    self.offerings.where("LOWER(format) LIKE?", "consulting")
  end

  def events
    self.offerings.where("LOWER(format) LIKE?", "%event")
  end

  def conferences
    self.offerings.where("LOWER(format) LIKE?", "%conference")
  end

  def add_slug
    update(slug: to_slug(self.name))
  end

  def to_param
    slug
  end

end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < ApplicationController

  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  def new
    @organization = Organization.new
    @organizations_categories = @organization.organizations_categories.new
    @categories = Category.all
  end

  def create
    @categories = Category.all
    @organization = Organization.new(organization_params)
    categories = params[:organization][:categories][:category_id]
    categories = categories.reject {|t| t.empty? }
    categories.each {|id| @organization.categories << Category.find(id) } if !categories.empty?
    if @organization.save
      redirect_to admin_dashboard_path
      flash[:success] = "Created new organization #{@organization.name}"
    else
      flash.now[:error] = @organization.errors.full_messages.first
      render :new
    end
  end

  def show
  end

  def edit
    @organizations_categories = @organization.organizations_categories
    @categories = Category.all
  end

  def update
    @categories = Category.all
    @organization.update(organization_params)
    categories = params[:organization][:organizations_categories][:category_id]
    @organization.categories = []
    categories = categories.reject {|t| t.empty? }
    categories.each {|id| @organization.categories << Category.find(id) } if !categories.empty?
    flash[:success] = "Successfully updated #{@organization.name}"
    redirect_to admin_organization_path(@organization)
  end

  private

    def organization_params
      params.require(:organization).permit(:name,
        :website,
        :twitter,
        :instagram,
        :facebook,
        :description,
        :history,
        :avatar,
        :categories,
        category_ids: [:id, :name])
    end

    def set_organization
      # @organization = Organization.find_by(slug: params[:slug])

      @organization = Organization.find(params[:id])
    end

end

app/controllers/organizations/offerings_controller.rb
class Organizations::OfferingsController < ApplicationController

  def show
    @offering = Offering.find_by(slug: params[:slug])
    # @offering = Offering.find(params[:id])
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def show
    @organization = Organization.find_by(slug: params[:slug])
    @similar = Organization.search_similar(@organization)
  end

  def index
    @categories = Category.all
    @featured = Organization.last
    if params[:category]
      @organizations = Organization.filter(params[:category][:category_id])
      @organizations = @organizations.paginate(:page => params[:page], :per_page => 15)
    else
      @organizations = Organization.paginate(:page => params[:page], :per_page => 15).order('name ASC')
    end
    if params[:sort]
      sort_orgs
    end
    if params[:search]
      search_orgs
    end
  end

  private

    def sort_orgs
      if params[:sort][:sort_order] == "Alphabetical (Z-A)"
        @organizations = Organization.paginate(:page => params[:page], :per_page => 15).order('name DESC')
      else
        @organizations = Organization.paginate(:page => params[:page], :per_page => 15).order('name ASC')
      end
    end

    def search_orgs
      @organizations = Organization.by_search(params[:search]).order('name ASC')
      @organizations = @organizations.paginate(:page => params[:page], :per_page => 15)
    end

end

app/views/organizations/index.html.erb
<div class="container">

  <div class="well">
    <div class="featured-company">
      <h3 style="text-align:center; padding-bottom: 20px;">FEATURED COMPANY</h3>
      <h3><%= @featured.name %></h3>
      <p><%= image_tag @featured.avatar.url(:medium) %></p>
    </div>
  </div>

  <div class="row text-center">
    <div class="search-form-company-index">
      <%= form_tag organizations_path, :method => :get do %>
        <%= text_field_tag :search, params[:search], id: "index_search_company", size: "50", style: "float: none; position: relative; vertical-align: top; height:36px;", placeholder: "Search Companies" %>
        <%= submit_tag "Search", :class => 'btn btn-info' %>
      <% end %>
      </form>
    </div>
  </div>

  <div class="row text-center" style="margin-top:1em;">
    <div class="col-md-6">
      <%= form_tag organizations_path, method: "get" do %>
        <%= select("category", "category_id", @categories.collect {|p| [ p.name, p.id ] }, {prompt: 'Filter By Category'}, {:onchange => "this.form.submit();"}) %>
        <button id="show-all-orgs" class="btn btn-success"><%= link_to "All", organizations_path %></button>
      <% end %>
    </div>

    <div class="col-md-6">
      <div class="sort-company-list">
        <%= form_tag organizations_path, method: "get" do %>
          <%= select("sort", "sort_order", ["Alphabetical (A-Z)","Alphabetical (Z-A)"], {prompt: 'Sort Companies'}, {:onchange => "this.form.submit();"}) %>
        <% end %>
      </div>
    </div>
  </div>

  <hr>

  <div class="row row-eq-height">
    <% @organizations.each do |organization| %>
    <div class="col-md-4">
    <h4 style="font-weight:200; padding-bottom:10px;"><%= link_to organization.name.titleize, organization_path(organization) %></h4>
    <%= image_tag organization.avatar.url(:square) %>
    <p><%#= organization.description %></p>
    </div>
    <% end %>
  </div>

  <div class="pagination-orgs">
    <%= will_paginate @organizations %>
  </div>
</div>

app/views/organizations/show.html.erb
<div class="container" style="margin-top:-2em;">
  <div class="row">
    <div class="col-md-8">
      <h4 style="padding-bottom:1em;"><%= @organization.name.titleize %></h2>
        <%= image_tag @organization.avatar.url(:square) %>
            <div id="exTab1">
            <ul  class="nav nav-tabs" style="padding-top:30px; font-family: 'Signika', sans-serif;">
          		<li class="active">
                <a  href="#tab-info" data-toggle="tab">company info</a>
          		</li>
          		<li>
                <a href="#tab-offerings" data-toggle="tab">events & happenings</a>
          		</li>

            </ul>

          	<div class="tab-content clearfix" style="padding-top:30px; font-family:Helvetica; font-weight:lighter">
          	  <div class="tab-pane active" id="tab-info" >
                <p><%= @organization.history %></p>
          		</div>
          		<div class="tab-pane" id="tab-offerings">
                <div class="well" id="offering-courses" >
                  <h4 id="offering-courses-title"><strong>COURSES</strong></h4>
                    <% if @organization.courses != nil %>
                      <% @organization.courses.each do |course| %>
                        <p><%= link_to course.name, organizations_offering_path(course) %> </p>
                        <p> <% if course.date %> <%= course.date.strftime("%m/%d/%Y") %><% end %>, for <%= course.length %> </p>

                      <% end %>
                    <% end %>
                </div>
                <div class="well" id="offering-courses" >
                  <h4 id="offering-courses-title"><strong>WORKSHOPS</strong></h4>
                    <div class="row">
                      <% if @organization.workshops != nil %>
                        <% @organization.workshops.each do |workshop| %>
                          <div class="col-md-4"><%= workshop.name %> </div>
                          <div class="col-md-4"><% workshop.tags.each do  %>
                          <%= tag.name %> <% end %></div>
                          <div class="col-md-4"><%= workshop.date %> </div>
                        <% end %>
                      <% end %>
                    </div>
                </div>
                <div class="well" id="offering-courses" >
                  <h4 id="offering-courses-title"><strong>CONFERENCES</strong></h4>
                    <% if @organization.conferences != nil %>
                      <% @organization.conferences.each do |conference| %>
                      <p><%= link_to conference.name, organizations_offering_path(conference) %> </p>
                      <p>  <% if conference.date %> <%= conference.date.strftime("%m/%d/%Y") %><% end %>, for <%= conference.length %> </p>
                      <% end %>
                    <% end %>
                </div>
          		</div>

              <div class="tab-pane" id="tab-events">
                <% if @organization.courses != nil %>
                  <% @organization.courses.each do |course| %>
                    <p><%= link_to course.name, organizations_offering_path(course) %> </p>
                    <p> <% if course.date %> <%= course.date.strftime("%m/%d/%Y") %> <% end %>, for <%= course.length %> </p>

                  <% end %>
                <% end %>
                <ul>
                  <li>event 1</li>
                  <li>event 2</li>
                </ul>
          		</div>

          	</div>
          </div>
          <br>
      <div class="well" id="offering-details">
        <h4 id="offering-details-title"><strong>BEHIND THE SCENES</strong></h4>
          <p style="font-family:Helvetica; font-weight:lighter"> <%= @organization.description %> </p>
      </div>
      <div class="well" id="offering-details">
        <h4 id="offering-details-title"><strong>OTHER RESOURCES</strong></h4>
          <p style="font-family:Helvetica; font-weight:lighter"> Twitter: <%=  link_to @organization.twitter %> </p>
          <p style="font-family:Helvetica; font-weight:lighter"> Instagram: <%=  link_to @organization.instagram %> </p>
          <p style="font-family:Helvetica; font-weight:lighter"> Facebook: <%=  link_to @organization.facebook %> </p>
      </div>
  </div>

    <div class="col-md-4" style="text-align:left;">
      <div class="well" id="reserve-spot-div">
      <h4 id="reserve-spot-title" style="padding-top:25px; font-family: 'Signika', sans-serif;"> visit the <%=  link_to 'website', "#{@organization.website}", target: '_blank' %></h4>
    </div>
    <h5 id="similar-offerings"> Similar Organizations</h5>
    <% if @similar != nil %>
      <% @similar.each do |similar| %>
        <div class="well similar-offerings">
            <%= image_tag(similar.avatar.url, size: "100x100") %>

          <h5 style="text-align:center;"><span style="padding-right:0.5em; font-family:'Lora', serif;"><%= link_to similar.name.upcase, organization_path(similar) %> </span><span style="padding-left:0.5em;"></span> </h5>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>